# name: Create Release

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Create GitHub Release
#         uses: softprops/action-gh-release@v2
#         with:
#           draft: false
#           prerelease: false
